name = "kiya-net"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

# ========================
# ENVIRONMENT VARIABLES
# ========================
[vars]
NEXT_PUBLIC_APP_URL = "https://kiya-net.workers.dev"

# ========================
# PRODUCTION
# ========================
[env.production]
vars = { NEXT_PUBLIC_APP_URL = "https://kiya-net.workers.dev" }
